apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-app
  labels:
    app: tutorial-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tutorial-app
  template:
    metadata:
      labels:
        app: tutorial-app
    spec:
      containers:
      - name: tutorial-app
        image: tutorial-app:latest
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
          value: "false"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: models-volume
          mountPath: /app/models
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: tutorial-app-data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: tutorial-app-models-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-backend
  labels:
    app: tutorial-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutorial-backend
  template:
    metadata:
      labels:
        app: tutorial-backend
    spec:
      containers:
      - name: tutorial-backend
        image: tutorial-app:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        command: ["uvicorn", "src.tutorial_app.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-app-service
  labels:
    app: tutorial-app
spec:
  selector:
    app: tutorial-app
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tutorial-backend-service
  labels:
    app: tutorial-backend
spec:
  selector:
    app: tutorial-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutorial-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - tutorial-app.yourdomain.com
    secretName: tutorial-app-tls
  rules:
  - host: tutorial-app.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tutorial-app-service
            port:
              number: 8501
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-app-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-app-models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
